# Generated by Django 5.1.15 on 2026-01-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_questionnaire_gender_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnairechoice',
            name='label',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questionnairequestion',
            name='text',
            field=models.TextField(),
        ),
    ]
