# Generated by Django 5.1.15 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_questionnaire_multi_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairequestion",
            name="input_type",
            field=models.CharField(blank=True, default="choice", max_length=16),
        ),
    ]
