# Generated by Django 5.1.15 on 2026-02-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_questionnaire_input_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ui_theme",
            field=models.CharField(choices=[("dark", "Тёмная"), ("light", "Светлая")], default="dark", max_length=16),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_email_matches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_email_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notify_email_marketing",
            field=models.BooleanField(default=False),
        ),
    ]
