# Generated by Django 5.1.15 on 2026-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesection',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
