# Generated by Django 5.1.5 on 2026-07-01 17:39

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_questionnaire_visibility_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='questionnaire_ideal',
            field=accounts.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='questionnaire_me',
            field=accounts.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProfileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('profile_view', 'Просмотр профиля'), ('questionnaire_view', 'Просмотр анкеты'), ('profile_edit', 'Редактирование профиля'), ('questionnaire_edit', 'Редактирование анкеты')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='profiles.profile')),
            ],
            options={
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['profile', 'accessed_at'], name='profiles_pr_profile_9b3367_idx'), models.Index(fields=['accessed_by', 'accessed_at'], name='profiles_pr_accesse_b67795_idx'), models.Index(fields=['accessed_at'], name='profiles_pr_accesse_ff97a5_idx')],
            },
        ),
    ]
