# Generated by Django 5.1.5 on 2026-08-04 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_questionnaire_visibility_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
