# Generated by Django 5.1.5 on 2026-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profilephoto_moderated_at_profilephoto_moderated_by_and_more'),
        ('profiles', '0011_encrypt_existing_questionnaires'),
    ]

    operations = [
    ]
