# Generated by Django 5.1.5 on 2026-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_revert_questionnaire_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sensitive_data_visibility',
            field=models.CharField(blank=True, choices=[('everyone', 'Всем зарегистрированным пользователям'), ('nobody', 'Никому'), ('matches', 'Только совпадениям/симпатиям')], default='matches', max_length=16),
        ),
        migrations.DeleteModel(
            name='ProfileAccessLog',
        ),
    ]
