# Generated by Django 5.1.5 on 2026-09-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_sensitive_data_visibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sensitive_data_visibility',
        ),
        migrations.CreateModel(
            name='SectionVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexual_visibility', models.CharField(choices=[('everyone', 'Всем зарегистрированным пользователям'), ('nobody', 'Никому'), ('matches', 'Только совпадениям/симпатиям')], default='matches', max_length=16)),
                ('religious_visibility', models.CharField(choices=[('everyone', 'Всем зарегистрированным пользователям'), ('nobody', 'Никому'), ('matches', 'Только совпадениям/симпатиям')], default='matches', max_length=16)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_visibility', to='profiles.profile')),
            ],
        ),
    ]
