# Generated by Django 5.1.5 on 2026-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_profile_sensitive_data_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='native_language',
            field=models.CharField(blank=True, max_length=64, verbose_name='Родной язык'),
        ),
    ]
