# Generated by Django 5.1.15 on 2026-02-09 18:39

import django.db.models.deletion
from django.db import migrations, models


def seed_landing(apps, schema_editor):
    HomePage = apps.get_model("matchmaking", "HomePage")
    HomeBlock = apps.get_model("matchmaking", "HomeBlock")

    page, _ = HomePage.objects.get_or_create(slug="landing", defaults={"title": "Главная", "is_active": True})

    if HomeBlock.objects.filter(page=page).exists():
        return

    HomeBlock.objects.create(
        page=page,
        type="hero",
        order=10,
        is_active=True,
        badge="Найди мэтч за пару свайпов",
        title="Умные знакомства, которые выглядят дорого",
        body="Заполни анкету, свайпай, получай мэтчи и общайся в чате. Быстрое MVP на Django с современным интерфейсом.",
        primary_button_text="Создать аккаунт",
        primary_button_url="/accounts/register/",
        secondary_button_text="Войти",
        secondary_button_url="/accounts/login/",
        items=[
            {"kicker": "Мгновенно", "title": "Свайпы", "text": "Лайк/пас — в один клик"},
            {"kicker": "Без воды", "title": "Профили", "text": "Факты, фото, интересы"},
            {"kicker": "После мэтча", "title": "Чат", "text": "Пиши и договаривайся"},
        ],
    )

    HomeBlock.objects.create(
        page=page,
        type="steps",
        order=20,
        is_active=True,
        title="Как это работает",
        items=[
            {"kicker": "Шаг 1", "title": "Анкета", "text": "Заполни профиль и добавь фото"},
            {"kicker": "Шаг 2", "title": "Свайпы", "text": "Лайкай тех, кто нравится"},
            {"kicker": "Шаг 3", "title": "Чат", "text": "При мэтче — общайся сразу"},
        ],
    )

    HomeBlock.objects.create(
        page=page,
        type="list",
        order=30,
        is_active=True,
        title="Почему это удобно",
        items=[
            "Быстрый интерфейс без лишних экранов",
            "Акцент на анкете и реальном диалоге",
            "Модерация: жалобы, блокировки, баны",
        ],
    )

    HomeBlock.objects.create(
        page=page,
        type="grid",
        order=40,
        is_active=True,
        title="Почему мы",
        subtitle="Коротко — чем отличается подход.",
        items=[
            {"kicker": "Фокус", "title": "на серьёзность", "text": "меньше шума — больше смысла"},
            {"kicker": "Подбор", "title": "по анкете", "text": "рекомендации становятся точнее"},
            {"kicker": "Контроль", "title": "и безопасность", "text": "жалобы, блокировки, баны"},
        ],
    )

    HomeBlock.objects.create(
        page=page,
        type="cta",
        order=50,
        is_active=True,
        title="Мини‑совет",
        body="Заполни “Я”, потом “Мой идеал” — так совпадения обычно качественнее.",
        primary_button_text="Начать",
        primary_button_url="/accounts/register/",
        secondary_button_text="Войти",
        secondary_button_url="/accounts/login/",
    )

    HomeBlock.objects.create(
        page=page,
        type="faq",
        order=60,
        is_active=True,
        title="FAQ",
        items=[
            {
                "q": "Почему анкета важна?",
                "a": "Чем больше ответов, тем точнее рекомендации и проще начать разговор.",
                "open": True,
            },
            {
                "q": "Как написать первым?",
                "a": "Вопрос + конкретика (не “как дела?”) обычно работает лучше всего.",
                "open": False,
            },
            {
                "q": "Что с безопасностью?",
                "a": "Есть жалобы/блокировки/баны, а первые встречи лучше назначать в людных местах.",
                "open": False,
            },
        ],
    )

    HomeBlock.objects.create(
        page=page,
        type="cta",
        order=70,
        is_active=True,
        badge="Готов начать?",
        title="Создай профиль и получи первый мэтч",
        subtitle="Займёт меньше минуты.",
        primary_button_text="Регистрация",
        primary_button_url="/accounts/register/",
        secondary_button_text="Войти",
        secondary_button_url="/accounts/login/",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_remove_userrecommendation_unique_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('stats', 'Stats'), ('steps', 'Steps'), ('list', 'List'), ('grid', 'Grid'), ('faq', 'FAQ'), ('cta', 'CTA')], max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, default='', max_length=80)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=260)),
                ('body', models.TextField(blank=True, default='')),
                ('primary_button_text', models.CharField(blank=True, default='', max_length=60)),
                ('primary_button_url', models.CharField(blank=True, default='', max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, default='', max_length=60)),
                ('secondary_button_url', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('items', models.JSONField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='matchmaking.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['page', 'is_active', 'order'], name='matchmaking_page_id_29682f_idx')],
            },
        ),
        migrations.RunPython(seed_landing, migrations.RunPython.noop),
    ]
