# Generated by Django 5.1.15 on 2026-02-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_homepage_homeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_admin_chat',
            field=models.BooleanField(default=False),
        ),
    ]
