# Generated by Django 5.1.5 on 2026-08-04 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_match_is_admin_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecommendation',
            name='is_self_search',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminSearchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('surface', 'Поверхностный подбор'), ('targeted', 'Точечный подбор'), ('deep', 'Углублённый подбор')], max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('required_criteria', models.TextField(blank=True, default='', help_text='Для точечного подбора: обязательные критерии клиента (не менее двух).')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=16)),
                ('rejected_streak', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_search_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_search_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='matchmaking.adminsearchorder'),
        ),
        migrations.CreateModel(
            name='SelfSearchCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_compatibility_percent', models.PositiveSmallIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_search_criteria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfSearchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField()),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_search_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
