# Generated by Django 5.1.15 on 2026-02-07 00:00

from django.conf import settings
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(blank=True, default="", max_length=256)),
                ("expires_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_count", models.PositiveIntegerField(default=0)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(fields=["user", "created_at"], name="accounts_pas_user_id_5fcefe_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresetcode",
            index=models.Index(fields=["expires_at"], name="accounts_pas_expires_9d6d88_idx"),
        ),
    ]
