# Generated by Django 5.1.15 on 2026-02-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_password_reset_code"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="passwordresetcode",
            old_name="accounts_pas_user_id_5fcefe_idx",
            new_name="accounts_pa_user_id_8b0b73_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordresetcode",
            old_name="accounts_pas_expires_9d6d88_idx",
            new_name="accounts_pa_expires_d44861_idx",
        ),
    ]
