# Generated by Django 5.1.5 on 2026-07-01 17:39

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=accounts.fields.EncryptedEmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='event',
            field=models.CharField(choices=[('new_match', 'Новое совпадение'), ('new_message', 'Новое сообщение')], max_length=64),
        ),
    ]
