# Generated by Django 5.1.5 on 2026-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_privacy_accepted_at_and_more'),
        ('accounts', '0007_encrypt_existing_emails'),
    ]

    operations = [
    ]
