# Generated by Django 5.1.5 on 2026-09-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_revert_email_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='religious_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='religious_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religious_consent_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexual_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sexual_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexual_consent_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consentevent',
            name='kind',
            field=models.CharField(choices=[('terms', 'Пользовательское соглашение — принято'), ('privacy', 'Политика обработки персональных данных — принята'), ('special_category_given', 'Согласие на спецкатегории — дано'), ('special_category_revoked', 'Согласие на спецкатегории — отозвано'), ('sexual_consent_given', 'Согласие на сексуальные данные — дано'), ('sexual_consent_revoked', 'Согласие на сексуальные данные — отозвано'), ('religious_consent_given', 'Согласие на религиозные данные — дано'), ('religious_consent_revoked', 'Согласие на религиозные данные — отозвано')], max_length=32),
        ),
    ]
